# Site settings
title: 'inUtil, AI powered efficiency'
email: info@inutil.info
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://inutil.info" # the base hostname & protocol for your site

twitter_username: BotGasolin
github_username: inUtil-info
linkedin_username: botgasolin

# Build settings
markdown: kramdown
