# Site settings
title: 'FriquiFund'
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://friquifund.ml" # the base hostname & protocol for your site
email: "info@friquifund.ml"


# Build settings
markdown: kramdown
